# Generated by Django 6.0.2 on 2026-02-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableentry_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
    ]
